# Form implementation generated from reading ui file 'GL.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import sys
from PyQt6 import QtCore, QtGui, QtWidgets
import defs
from PyQt6.QtWidgets import QMainWindow, QApplication

class Ui_Gl(object):
    def setupUi(self, Gl):
        Gl.setObjectName("Gl")
        Gl.resize(900, 342)
        Gl.setMaximumSize(QtCore.QSize(900, 343))
        Gl.setStyleSheet("background-color: rgb(218,236,255);")
        self.centralwidget = QtWidgets.QWidget(parent=Gl)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 250, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(136,155,211); ")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 250, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(136,155,211); ")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 250, 220, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(136,155,211); ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(690, 250, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(136,155,211); ")
        self.pushButton_4.setObjectName("pushButton_4")
        Gl.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(lambda: defs.go_to_new_file("poisk_Ui.py"))
        self.pushButton_2.clicked.connect(lambda: defs.go_to_new_file("profile_Ui.py"))
        self.pushButton_3.clicked.connect(lambda: defs.go_to_new_file("redactirovanie.py"))
        self.pushButton_4.clicked.connect(QApplication.quit)

        self.retranslateUi(Gl)
        QtCore.QMetaObject.connectSlotsByName(Gl)

    def retranslateUi(self, Gl):
        _translate = QtCore.QCoreApplication.translate
        Gl.setWindowTitle(_translate("Gl", "MainWindow"))
        self.pushButton.setText(_translate("Gl", "Найти рецепт"))
        self.pushButton_2.setText(_translate("Gl", "Профиль"))
        self.pushButton_3.setText(_translate("Gl", "Редактировать базу"))
        self.pushButton_4.setText(_translate("Gl", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gl = QtWidgets.QMainWindow()
    ui = Ui_Gl()
    ui.setupUi(Gl)
    Gl.show()
    sys.exit(app.exec())
