# Form implementation generated from reading ui file 'podbor.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import defs
param = sys.argv[1]
class Ui_podbor(object):
    def setupUi(self, podbor, param):
        podbor.setObjectName("podbor")
        podbor.resize(907, 667)
        podbor.setMaximumSize(QtCore.QSize(907, 667))
        podbor.setStyleSheet("background-color: rgb(218,236,255);")
        self.centralwidget = QtWidgets.QWidget(parent=podbor)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 170, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 70, 491, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(246,250,255); ")
        self.textEdit.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(570, 220, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(246,250,255); ")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.currentIndexChanged.connect(lambda index: self.add_dish(index,param))
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(570, 350, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("background-color: rgb(246,250,255); ")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.currentIndexChanged.connect(lambda: self.vibor_dish())
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 300, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 40, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(246,250,255); ")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(730, 460, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(136,155,211);")
        self.pushButton.setObjectName("pushButton")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(750, 40, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("background-color: rgb(246,250,255); ")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 40, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(80, 590, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 590, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(136,155,211);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 460, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(136,155,211);")
        self.pushButton_3.setObjectName("pushButton_3")
        podbor.setCentralWidget(self.centralwidget)

        self.textEdit.setReadOnly(True)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_3.setReadOnly(True)
        

        self.radioButton.clicked.connect(lambda: defs.radioButton_cheked(self.textEdit_2.toPlainText(),self.textEdit_3.toPlainText()))
        self.radioButton.clicked.connect(lambda: self.vibor_dish())

        self.pushButton_2.clicked.connect(lambda: defs.add_favorite(self.comboBox_2.currentText()))
        self.pushButton_3.clicked.connect(lambda: defs.go_to_new_file("GL_Ui.py"))
        self.pushButton.clicked.connect(lambda: defs.go_to_new_file("poisk_Ui.py"))

        self.retranslateUi(podbor)
        QtCore.QMetaObject.connectSlotsByName(podbor)

    def retranslateUi(self, podbor):
        _translate = QtCore.QCoreApplication.translate
        podbor.setWindowTitle(_translate("podbor", "MainWindow"))
        self.label.setText(_translate("podbor", "Выберите категорию"))
        self.comboBox.setItemText(0, _translate("podbor", "Первые блюда"))
        self.comboBox.setItemText(1, _translate("podbor", "Вторые блюда"))
        self.comboBox.setItemText(2, _translate("podbor", "Закуски"))
        self.comboBox.setItemText(3, _translate("podbor", "Салаты"))
        self.comboBox.setItemText(4, _translate("podbor", "Напитки"))
        self.comboBox.setItemText(5, _translate("podbor", "Десерты"))
        self.label_2.setText(_translate("podbor", "Выберите блюдо"))
        self.pushButton.setText(_translate("podbor", "Назад"))
        self.label_3.setText(_translate("podbor", "Уровень рецепта:"))
        self.radioButton.setText(_translate("podbor", "Приготовлено"))
        self.pushButton_2.setText(_translate("podbor", "Добавить в избранное"))
        self.pushButton_3.setText(_translate("podbor", "На главную"))


    def add_dish(self,index,param):
        self.comboBox_2.clear()
        kategory= self.comboBox.itemText(index)
        fetch_dish=defs.vabor_category(kategory,param)
        for dish_name in fetch_dish:
            self.comboBox_2.addItem(dish_name[1])
    def vibor_dish(self):
        self.textEdit_2.clear()
        self.textEdit.clear()
        name_dish = self.comboBox_2.currentText()
        fetch_dish=defs.vivod_recipe(name_dish)
        if fetch_dish:
            self.textEdit_2.setText(fetch_dish[1])
            self.textEdit.setText(fetch_dish[3])
            self.textEdit_3.setText(str(fetch_dish[5]))
            if fetch_dish[7]==0:
                self.radioButton.setChecked(False)
                self.radioButton.setEnabled(True)
            else:
                self.radioButton.setChecked(True)
                self.radioButton.setEnabled(False)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    podbor = QtWidgets.QMainWindow()
    ui = Ui_podbor()
    ui.setupUi(podbor,param)
    podbor.show()
    sys.exit(app.exec())
